### ISSUE TITLE
I'm interested in contributing GitHub wiki-related actions

### ISSUE THREAD

**Issue by jcbhmr** [actions-ecosystem/.github#5]
Hello! 👋

I'm "shopping" around for cool GitHub Actions organizations so that these actions aren't stuck if I loose interest in it or am not active or whatever. This appears to be a single-contributor @actions-ecosystem organization, so sorry if I'm in the wrong spot here.

I am interested in adding GitHub Actions that would make it easy to sync a GitHub in-source folder like `/wiki/*.md` to the actual "wiki" tab on GitHub. This is useful for users who want to possibly:
- Autogenerate documentation but don't want to put it on GitHub Pages, so they put it on a wiki instead
- Allowing the normal GitHub flow of PRs + merges for wiki changes
- Letting users auto-generate other things like build data and post it to the wiki
- etc.

Particularily, there are 4 "things" that I see being useful to have actions for so that you can do something like this:

```yml
on:
  push:
    branches: "main"
    paths: wiki/**
jobs:
  source-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/source-to-wiki-links@v1
      - uses: actions-ecosystem/upload-wiki@v1
```
```yml
on:
  gollum: null
  schedule:
    - cron: "0 0 * * *"
jobs:
  wiki-to-source:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-ecosystem/download-wiki@v1
      - uses: actions-ecosystem/wiki-to-source-links@v1
      - uses: EndBug/add-and-commit@v9
```

## What you want to add

- action-source-to-wiki-links: Rewrites links like `./Hello.md` to be `./Hello` since GitHub wikis don't do file extensions; also renames README.md to Home.md
- action-(publish|push|upload)-wiki: Pushes current folder or subfolder to the GitHub wiki
- action-(download|clone|pull)-wiki: Pulls the GitHub wiki to the current folder or sub folder
- action-wiki-to-source-links: Rewrites links like `./Hello` to `./Hello.(md|markdown|mdown,etc)` to work in source control; also renames Home.md to README.md

## Why this is needed

Because there's currently no "the way to do it" for 👆👇 sync of a wiki. I think this would solve a problem that exists.

📬 pinging @micnncim directly since I see you're not "Watching" this repo
